export default [
  "Michael Jordan",
  "LeBron James",
  "Lionel Messi",
  "Cristiano Ronaldo",
  "Usain Bolt",
  "Serena Williams",
  "Roger Federer",
  "Kobe Bryant",
  "Tom Brady",
  "Muhammad Ali",
  "Neymar",
  "Alex Morgan",
  "Michael Phelps",
  "Simone Biles",
  "Venus Williams",
  "Stephen Curry",
  "Katie Ledecky",
  "Shaun White",
];
