export default [
  { name: "Michael Jordan", sport: "basketball" },
  { name: "LeBron James", sport: "basketball" },
  { name: "Lionel Messi", sport: "soccer" },
  { name: "Cristiano Ronaldo", sport: "soccer" },
  { name: "Usain Bolt", sport: "running track" },
  { name: "Serena Williams", sport: "tennis court" },
  { name: "Roger Federer", sport: "tennis court" },
  { name: "Kobe Bryant", sport: "basketball" },
  { name: "Tom Brady", sport: "football" },
  { name: "Muhammad Ali", sport: "boxing ring" },
  { name: "Neymar", sport: "soccer" },
  { name: "Alex Morgan", sport: "soccer" },
  { name: "Michael Phelps", sport: "swimming laps" },
  { name: "Simone Biles", sport: "gymnastics competition" },
  { name: "Venus Williams", sport: "tennis court" },
  { name: "Stephen Curry", sport: "basketball" },
  { name: "Katie Ledecky", sport: "downhill skiing" },
  { name: "Shaun White", sport: "snowboarding" },
];
