export default [
  { name: "Michael Jordan", sport: "basketball" },
  { name: "LeBron James", sport: "basketball" },
  { name: "Lionel Messi", sport: "soccer" },
  { name: "Cristiano Ronaldo", sport: "soccer" },
  { name: "Usain Bolt", sport: "running track" },
  { name: "Serena Williams", sport: "tennis match" },
  { name: "Roger Federer", sport: "tennis match" },
  { name: "Kobe Bryant", sport: "basketball" },
  { name: "Tom Brady", sport: "football" },
  { name: "Muhammad Ali", sport: "boxing gym" },
  { name: "Neymar", sport: "soccer" },
  { name: "Alex Morgan", sport: "soccer" },
  { name: "Michael Phelps", sport: "swimmer" },
  { name: "Simone Biles", sport: "gymnast" },
  { name: "Venus Williams", sport: "tennis match" },
  { name: "Stephen Curry", sport: "basketball" },
  { name: "Katie Ledecky", sport: "ski jump" },
  { name: "Shaun White", sport: "snowboard jump" },
];
